spring:
  profiles:
    active: local
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: library-events-listner-group
      properties:
        spring:
          json:
            value:
              default:
                type: org.example.libraryeventsconsumer.domain.LibraryEvent
            use:
              type:
                headers: false
    listener:
      ack-mode: manual
      concurrency: 3

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: dev:9092,dev:9093,dev:9094
