spring:
  profiles:
    active: local
  kafka:
    template:
      default-topic: library-events
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.example.libraryeventsproducer.serialization.LibraryEventSerializer
---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
---
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: dev:9092,dev:9093,dev:9094
