POST http://localhost:8080/v1/async-library-event
Content-Type: application/json

{
  "id": null,
  "book": {
    "id": 1,
    "name": "War and world",
    "author": "Tolstoy"
  }
}

###
POST http://localhost:8080/v1/sync-library-event
Content-Type: application/json

{
  "id": null,
  "book": {
    "id": 2,
    "name": "War and world",
    "author": "Tolstoy"
  }
}

